name: OrbSuite
main: net.krinsoft.orbsuite.OrbCore
version: maven-version-number
author: krinsdeath

commands:
  orbsuite:
    aliases: [orb]
    description: OrbSuite's top level command.
    usage: /<command> ...
    
permissions:
  orbsuite.check.other:
    description: Allows a user to check another user's balance.
    default: op